version: '3'

services:
  vcenter:
    image: cblomart/vcsim
    deploy:
      restart_policy:
        delay: 5s
        max_attempts: 3
        window: 30s

  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "80"
    deploy:
      restart_policy:
        delay: 5s
        max_attempts: 3
        window: 30s

  vsphere-graphite:
    image: cblomart/vsphere-graphite:788a410 
    environment:
      - VCENTER_VCSIM=user:pass@vcenter:8989
      - BACKEND_TYPE=graphite
      - BACKEND_HOSTNAME=graphite
      - BACKEND_PORT=2003
    depends_on:
      - vcenter
      - graphite
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 3
        window: 120s
